Repository udacity/deep-learning, pull requests merged in 2021-02, with the labels that each got.

#257 Fix some typo and punctuation for consistency
  batch-norm/Batch_Normalization_Lesson.ipynb
Labels: enhancement

#278 Docs: Fix typo in notebook for sentiment network
  sentiment-network/Sentiment_Classification_Projects.ipynb
  sentiment-network/Sentiment_Classification_Solutions.ipynb
Labels: enhancement

#203 [small] quick grammar on output layer
  image-classification/dlnd_image_classification.ipynb
Labels: typo

#277 Fix the image width so that it is rendered properly
  first-neural-network/Your_first_neural_network.ipynb
Labels: enhancement

#185 Fixing typo on Sentiment RNN.
  sentiment-rnn/Sentiment_RNN.ipynb
  sentiment-rnn/Sentiment_RNN_Solution.ipynb
Labels: typo

#236 Fixed the DeprecationWarning while training
  first-neural-network/Your_first_neural_network.ipynb
Labels: bug :bug:
